### ISSUE TITLE
Duplicated lines

### ISSUE THREAD

**Issue by paulocoutinhox** [raygerlabs/templatepp#26]
Hi,

There is duplicated lines:
https://github.com/raygerlabs/templatepp/blob/master/CMakeLists.txt#L31-L32

Thanks.

**Comment by raygerlabs** [comment]
Hi,

Duplicated lines fixed. But I opened a question about this. I am unsure if we want this suppression or not. Honestly I find this a bit uncomfortable when I open the code in Visual Studio and I cannot modify CMake files there.

**Comment by paulocoutinhox** [comment]
There is more one thing:

```
set_property(GLOBAL PROPERTY USE_FOLDERS ON)
set(CMAKE_SUPPRESS_REGENERATION ON)
set(CMAKE_VERBOSE_MAKEFILE ON)
```

Maybe you can group all `set(CMAKE_XYZ` in the same group and at least `set_property`.

This way:

```
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(CMAKE_CXX_VISIBILITY_PRESET hidden)
set(CMAKE_VISIBILITY_INLINES_HIDDEN ON)
set(CMAKE_SUPPRESS_REGENERATION ON)
set(CMAKE_VERBOSE_MAKEFILE ON)
set_property(GLOBAL PROPERTY USE_FOLDERS ON)
```

or 

```
set_property(GLOBAL PROPERTY USE_FOLDERS ON)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(CMAKE_CXX_VISIBILITY_PRESET hidden)
set(CMAKE_VISIBILITY_INLINES_HIDDEN ON)
set(CMAKE_SUPPRESS_REGENERATION ON)
set(CMAKE_VERBOSE_MAKEFILE ON)
```

**Comment by raygerlabs** [comment]
Please see this PR https://github.com/raygerlabs/templatepp/pull/36
All options moved to separate cmake file.
