### ISSUE TITLE
Keep always version 1.0.0

### ISSUE THREAD

**Issue by paulocoutinhox** [raygerlabs/templatepp#40]
Hi,

My suggestion is to always keep version 1.0.0.

After a release, you only need delete the tag, enter on release and publish that github action will run it again and will upload new assets.

To me is very confuse that you will have a lot of releases that no one will use that in their projects. Who is that binary for a project?

What you think?

Thanks.

**Comment by raygerlabs** [comment]
@paulocoutinhox Hi, I agree with you completely! I was just testing if my jobs were working OK.
